# Generated by Django 3.2 on 2021-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('bought_from', models.CharField(max_length=10)),
                ('bought_on', models.CharField(default='', max_length=15)),
                ('price', models.CharField(default='', max_length=15)),
                ('gst_applied', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
