# Generated by Django 3.2 on 2021-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('destination', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('price', models.CharField(default='', max_length=15)),
                ('rt_pcr', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
